### ISSUE TITLE
LQR 제어기의 최적 입력 u에 대한 질문

### ISSUE THREAD

**Issue by scKim33** [scKim33/linearADP#5]
LQR 제어기에서 u = K(x-x_ref) 와 같이 입력을 두었을 때 반드시 x가 x_ref로 수렴하나요?
현재 짠 코드에서는 정상 상태 오차가 계속 나타납니다...

**Comment by hnlee77** [comment]
> LQR 제어기에서 u = K(x-x_ref) 와 같이 입력을 두었을 때 반드시 x가 x_ref로 수렴하나요? 현재 짠 코드에서는 정상 상태 오차가 계속 나타납니다...

현재 코드상에서 단위 등에서 살짝 오류가 있어보여서 #4 의 코멘트를 먼저 수정하고, 이 PR을 머지한 후에 LQR 제어기를 마저 설계해 봅시다~

**Comment by hnlee77** [comment]
우선 간단하게 말씀드리면 LQR 제어기는 원점으로 보내도록 하는, 다시 말해서, regulation을 목적으로 하는 제어기입니다. 따라서 원하는 기준궤적 또는 기준 값으로 수렴하기 위한 제어기를 위해서는 Integrator 같은 것이 추가적으로 필요합니다.
