### ISSUE TITLE
Progress Report 1 검토

### ISSUE THREAD

**Issue by scKim33** [scKim33/linearADP#9]
교수님께서 목요일 오후 2시에 보자고 하셔서

그 전까지 검토가 완료되어야 할 것 같습니다..

notion에 파일로 올려두었습니다

**Comment by hnlee77** [comment]
노션에 [코멘트 파일](https://www.notion.so/Progress-report-1-a65fc09662a3438695425c7593e688e3#911ae826f9e3401c801d7f91758e10dc) 추가로 올려놓았어요~
이대로 검토받으시면 될 것 같아요. 수고하셨습니다.
